baseurl = "https://nanx.me/"
publishDir = "public"
title = "Nan Xiao | 肖楠"
author = "Nan Xiao"
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "hugo-nanx2020"

enableEmoji = true
hasCJKLanguage = true

disqusShortname = "nan-xiao-blog"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
pagetitle = "Nan Xiao"
copyright = "© 2020 Nan Xiao"
faviconfile = "image/favicon.png"
logofile = "image/nanxiao.jpg"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "nanxstats"
twitter = "nanxstats"
linkedin = "nanxstats"
contact = "me@nanx.me"

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 1

[[menu.primary]]
identifier = "software"
name = "Software"
url = "/software/"
weight = 2

[[menu.primary]]
identifier = "papers"
name = "Papers"
url = "/papers/"
weight = 3

[[menu.primary]]
identifier = "talks"
name = "Talks"
url = "/talks/"
weight = 4

[[menu.primary]]
identifier = "books"
name = "Books"
url = "/books/"
weight = 5
